### ISSUE TITLE
impressum / contact for server admin and/or moderators

### ISSUE THREAD

**Issue by vv01f** [nek0/eidolon#12]
just some juristictions need contact data etc. to be provided

**Comment by nek0** [comment]
Yeah. I forgot that totally. Will fix.

**Comment by vv01f** [comment]
more important it is not hardcoded but setup enforced for anyone who runs the eidolon

**Comment by nek0** [comment]
It will get at least one entry in `config/settings.yml`

**Comment by nek0** [comment]
There is now a contact email setting.

**Comment by nek0** [comment]
I assume that this suffices and close this issue.

**Comment by s72785** [comment]
example for a good impressum (in Germany) http://www.kulturbuero-dresden.de/impressum.html
