### ISSUE TITLE
bug: datasec info for signup

### ISSUE THREAD

**Issue by vv01f** [nek0/eidolon#13]
maybe here not as a judical text but plain explaination that can easily be understood

some juristictions make it mandatory to include a declaration what data is used how and for what. especially cookies are regarded by e.g. belgium on account of a guideline by european union.

example: https://www.surespot.me/documents/threat.html

**Comment by nek0** [comment]
This is not really a bug. I didn't know better. Will be added.

**Comment by nek0** [comment]
I have added some sort of data threat analysis. is this enough?

**Comment by s72785** [comment]
this reads nice, minor things could be improved later maybe.

**Comment by nek0** [comment]
If you come up with anything, just drop me a message.
