### ISSUE TITLE
bug: reload after upload amiss

### ISSUE THREAD

**Issue by s72785** [nek0/eidolon#17]
after filling the upload form the reload did not happen, that was with e.g. item 39.

**Comment by nek0** [comment]
What exactly happened? When handling large files, it can take quite some time for the server to respond.

**Comment by s72785** [comment]
mh, not happening any more the same way

now it is

* whereever I started upload, e.g. inside an album
* after upload redirection leads to /

**Comment by nek0** [comment]
Where do you want to be led when your upload is complete?

**Comment by s72785** [comment]
back where I came from would be expected usually, like the album or user profile I was in right before.
where that was should be in e.g. the HTTP referer .

**Comment by nek0** [comment]
is fixed in version 0.1.5.5
