### ISSUE TITLE
request: speaking names as URI instead of numbers

### ISSUE THREAD

**Issue by s72785** [nek0/eidolon#19]
like user-name or album-name

e.g.
- /user-name/
- or /user-name/album-name/

instead of 
- /profile/1
- /album/1

would be nice

**Comment by nek0** [comment]
for users ther exists a /user/<username> handle, whoch leads to the profile page, but i canÄt do this for albums too, because album names are non-unique.

**Comment by vv01f** [comment]
yes you can as albums are in the namespace of the user and it sounds weired to have two albums of the same name for one user but no problem would be

* /nek0/babyalbum/
* /vv01f/babyalbum/

**Comment by nek0** [comment]
the Problem is still you CAN have two albums of the same name. The database doesn't care about the album names so much. I am willing to make changes, but I like to have the corners covered.

**Comment by vv01f** [comment]
same as for usernames on signup, it needs either a check on create or a solution at db level that throws an error eidolon can present/handle

**Comment by nek0** [comment]
new url added as follows:
/user/<username>/album/<albumname>
