### ISSUE TITLE
Simply running a SHA-1 HMAC on a password is not state-of-the-art.

### ISSUE THREAD

**Issue by horazont** [nek0/eidolon#20]
See the answer to ["Question 2" here](https://security.stackexchange.com/a/3168/11499). The TL;DR is that using a salted HMAC construct is good, but not good enough. It avoids cracking many passwords at once, but it does not protect against attacks on single passwords.

The point being that a single HMAC round is not expensive to calculate, and the attack can easily be parallelised on e.g. a GPU.

See also [this answer](https://security.stackexchange.com/a/16817/11499), which goes into the details on the why and how and lists alternatives such as PBKDF2, scrypt and bcrypt (all linked in the above answer). [There is also the rather new-ish argon2 scheme, but as always, new schemes are not immediately to be trusted.](https://security.stackexchange.com/q/107337/11499)

---

The authentication scheme looks clever (I don’t know if it _is_ clever though), but you might want to check out the [SCRAM SASL](https://tools.ietf.org/html/rfc5802) mechanism.

**Comment by nek0** [comment]
Thanks for pointing that out. I think I will focus on that now.

**Comment by vv01f** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=38662783)](https://www.bountysource.com/issues/38662783-simply-running-a-sha-1-hmac-on-a-password-is-not-state-of-the-art?utm_source=38662783&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by nek0** [comment]
HMAC-SHA1 has been successfully migrated to HMAC-Keccak. I hope this sufices for some years.

**Comment by s72785** [comment]
I guess for the bounty you have to join that other site
