### ISSUE TITLE
no js, no login, no error msg

### ISSUE THREAD

**Issue by s72785** [nek0/eidolon#24]
if js is needed, this should be shown with a `<noscript class="nojs">` area with information. this can be hidden with js in case.
also when server receives some false login there should be a msg stating what went wrong.

**Comment by nek0** [comment]
Issue with false login is fixed. Nojs issue is just next down the road.

**Comment by nek0** [comment]
There are now very visible warnings, when trying to log in or sign up with javascript enabled. I think that fixes it.

**Comment by s72785** [comment]
I doubt anyone would guess why login fails

**Comment by nek0** [comment]
sorry. I forgot to deploy the javascript correctly. should be working now.
