### ISSUE TITLE
login without js

### ISSUE THREAD

**Issue by s72785** [nek0/eidolon#25]
* warn and hint on mitm possibility (raise general awareness)
* give option to login anyway, even without js (e.g. for tor users)
* constraint: js optional always 
* same for registration and activation

**Comment by nek0** [comment]
This can be done, but I don't see the real benefit here.

**Comment by s72785** [comment]
the benefit is: do not rely on js only. not everyone can enable single scripts selectively or check them. trust base for optional stiff is better.

**Comment by nek0** [comment]
even tbb has javascript enabled by default. This is partly due to privacy concers. You get a fair warning if trying to log in to eidolon without js enabled. The source code for login and signup are freely available and can be checked for maliciousness.

**Comment by s72785** [comment]
according to https://www.torproject.org/docs/faq#TBBJavaScriptEnabled
this is not intended for privacy but for usability; this issue is about the opposite.
=> wontuse

**Comment by nek0** [comment]
I'll do it just for you and my boredom.

**Comment by nek0** [comment]
done. Have fun with your insecure login...
