### ISSUE TITLE
missing: suche

### ISSUE THREAD

**Issue by vv01f** [nek0/eidolon#3]
ich würde gerne (auch selectiv) Bezeichnungen, Dateinamen, Lizenzen, Kommentare, Beschreibungen etc. durchsuchen

festgestellt beim Mediagobblin auf der suche nach Bildern der Spendenbox

**Comment by nek0** [comment]
Ich versuche gerade mein bestes elasticsearch zum laufen zu bekommen.

**Comment by nek0** [comment]
wurde implementiert.
