### ISSUE TITLE
encourage strong passwords or frequent change

### ISSUE THREAD

**Issue by s72785** [nek0/eidolon#40]
* users could be made aware of the strength of their password (graphical indication)
* additionally the time it is regarded valid before asking for a new password can be shown (long/complex ones valid longer)
* when passwords are not valid any more the user might be notified (optional) of that circumstance
* change might be anecouraged especially on 5th of may each year, e.g. if password is older than a year

s.a. https://passwordday.org/

**Comment by nek0** [comment]
frequent changing of passwords, especially weak ones, doesn't really improve security (see [in this arsTechnica article][at]).

Checking passwords for strength would require me to incorporate more JavaScript. I wouldn't like to do that.

Overall these are some interesting proposals, but I don't think, they would improve neither security nor usefulness of this Project.

[at]:(https://arstechnica.com/information-technology/2016/08/frequent-password-changes-are-the-enemy-of-security-ftc-technologist-says/)
