### ISSUE TITLE
upload freez

### ISSUE THREAD

**Issue by s72785** [nek0/eidolon#42]
when uploading into an album ("Sticker" for that one) the upload might just pend and stop, form stays open and nothing happened.

assumption: server not reachable but no msg on js side given.

**Comment by nek0** [comment]
patience is a virtue.
It might be the case, that the server is still processing your image, while the form is still open.
This is especially the case with large files.

**Comment by s72785** [comment]
unfortunately 
… eidolon ist (still) down

> http://eidolon.nek0.eu/ can not be accessed, the website, it is probably broken...

**Comment by nek0** [comment]
strange server outage detected. eidolon is up and running again.
