### ISSUE TITLE
uggly preview

### ISSUE THREAD

**Issue by s72785** [nek0/eidolon#46]
it seems to be jpg: https://eidolon.nek0.eu/medium/119

**Comment by nek0** [comment]
I have experimented a bit and came up with a custom scaling method, which scales the images using a bilinear algorithm. The image looks a bit better now, but the key problem is, that the original svg is set to a small size.

I don't scale the uploaded svg images up to the size of the preview images before rendering them, but afterwards.

**Comment by nek0** [comment]
fixed.
