### ISSUE TITLE
feature request: upload from web source

### ISSUE THREAD

**Issue by vv01f** [nek0/eidolon#9]
just add an image e.g. from another media server and accept the URI of a file for download to eidolon directly.

**Comment by nek0** [comment]
Eidolon is about serving original content and not rips, snippets and bits of other sites. I don't see the point.

**Comment by s72785** [comment]
migrating from media.c3d2 to eidolon was the thought

**Comment by nek0** [comment]
migrating from one service to another should be done with a script of some sorts. Something where you have direct access to the database.
